#!/usr/bin/env bash
source <(curl -s https://raw.githubusercontent.com/rafaelmorales95/rudder_prox/refs/heads/main/rudder_prox)
# Copyright (c) 2021-2024 tteck
# Author: RafaelAdonai (adonai)
# License: MIT

function header_info {
clear
cat <<"EOF"
   _____           _     _             
  |  __ \         | |   (_)            
  | |__) |__  _ __| |__  _ _ __   __ _ 
  |  _  // _ \ '__| '_ \| | '_ \ / _` |
  | | \ \  __/ |  | | | | | | | | (_| |
  |_|  \_\___|_|  |_| |_|_|_| |_|\__, |
                                  __/ |
                                 |___/ 
       Rudder Server - Configuration Management
EOF
}
header_info
echo -e "Loading..."
APP="Rudder Server"
var_disk="8"
var_cpu="2"
var_ram="4096"
var_os="debian"
var_version="12"
variables
color
catch_errors

function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN="rudder-server"
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  APT_CACHER_IP=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="yes"
  VERB="no"
  echo_default
}

function update_script() {
header_info
echo "Rudder updates are managed through apt. Run 'apt update && apt upgrade' inside the container."
exit
}

start
build_container

LXC_CONFIG_PATH="/etc/pve/lxc/${CT_ID}.conf"

pct exec $CT_ID -- bash -c "
apt update
apt install -y curl gnupg apt-transport-https ca-certificates lsb-release

curl -fsSL https://repository.rudder.io/apt/rudder-apt.key | gpg --dearmor -o /usr/share/keyrings/rudder-archive-keyring.gpg

echo 'deb [signed-by=/usr/share/keyrings/rudder-archive-keyring.gpg] https://repository.rudder.io/apt/6.2/ $(lsb_release -cs) main' > /etc/apt/sources.list.d/rudder.list

apt update
DEBIAN_FRONTEND=noninteractive apt install -y rudder-server-root
"

pct exec $CT_ID -- systemctl enable rudder-jetty
pct exec $CT_ID -- systemctl start rudder-jetty

description

msg_ok "Rudder Server installation completed!\n"
echo -e "You can access the Rudder Web UI using the following URL:
         ${BL}https://${IP}:8080${CL}\n"
