#!/usr/bin/env bash
source <(curl -s https://raw.githubusercontent.com/tteck/Proxmox/main/misc/build.func)
# Autor: Adaptado para instalar Rudder Server automáticamente

function header_info {
clear
cat <<"EOF"
   ____           __    __               
  / __ \___  ____/ /___/ /___ _____  ___ 
 / / / / _ \/ __  / __  / __ `/ __ \/ _ \
/ /_/ /  __/ /_/ / /_/ / /_/ / / / /  __/
\____/\___/\__,_/\__,_/\__,_/_/ /_/\___/ 
                                         
      AUTO INSTALLADOR - RUDDER SERVER    
EOF
}
header_info
echo -e "Cargando...\n"

APP="Rudder"
var_disk="10"          # GB
var_cpu="2"
var_ram="2048"         # MB
var_os="debian"
var_version="12"

variables
color
catch_errors

function default_settings() {
  CT_TYPE="1"
  PW="rudder2024!"      # Contraseña root predefinida
  CT_ID=$NEXTID
  HN="rudder"
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="yes"            # Habilitar acceso SSH
  VERB="no"
  echo_default
}

start
build_container
description

### POST-INSTALLACIÓN AUTOMÁTICA DENTRO DEL CONTENEDOR
msg_info "Instalando y configurando Rudder Server (esto puede tardar)..."

lxc-attach -n $CT_ID -- bash -c "
apt update &&
apt install -y wget curl gnupg2 sudo ca-certificates lsb-release apt-transport-https &&
wget https://repository.rudder.io/tools/rudder-setup &&
chmod +x rudder-setup &&
./rudder-setup setup-server latest
"

msg_ok "Rudder Server instalado"

### MOSTRAR ACCESO
IP=$(pct exec $CT_ID -- hostname -I | awk '{print $1}')
echo -e "\n${APP} instalado correctamente 🎉"
echo -e "🔗 Interfaz web:   ${BL}https://${IP}/rudder${CL}"
echo -e "👤 Usuario web:    ${GN}admin${CL}"
echo -e "🔑 Contraseña web: ${GN}admin${CL} (cámbiala al ingresar)"
echo -e ""
echo -e "📡 Acceso SSH:     ${GN}ssh root@${IP}${CL}"
echo -e "🔐 Contraseña SSH: ${GN}rudder2024!${CL}"
msg_ok "Finalizado correctamente"
