#!/usr/bin/env bash
source <(curl -s https://raw.githubusercontent.com/tteck/Proxmox/main/misc/build.func)
# Copyright (c) 2021-2024 tteck
# Author: tteck (tteckster)
# License: MIT
# https://github.com/tteck/Proxmox/raw/main/LICENSE

function header_info {
clear
cat <<"EOF"
    ____           __     __            
   / __ \___  ____/ /__  / /_____  _____
  / /_/ / _ \/ __  / _ \/ __/ __ \/ ___/
 / _, _/  __/ /_/ /  __/ /_/ /_/ / /    
/_/ |_|\___/\__,_/\___/\__/\____/_/     

     Rudder Server Installer
EOF
}
header_info
echo -e "Loading..."
APP="Rudder"
var_disk="8"
var_cpu="2"
var_ram="4096"
var_os="debian"
var_version="12"
variables
color
catch_errors

function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  APT_CACHER_IP=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

function install_rudder() {
  header_info
  msg_info "Updating OS"
  apt-get update &>/dev/null
  apt-get upgrade -y &>/dev/null
  msg_ok "System Updated"

  msg_info "Installing Prerequisites"
  apt-get install -y curl gnupg2 wget lsb-release ca-certificates apt-transport-https sudo &>/dev/null
  msg_ok "Installed Prerequisites"

  msg_info "Adding Rudder Repository"
  curl -s https://packagecloud.io/install/repositories/rudder/rudder/script.deb.sh | bash &>/dev/null
  msg_ok "Rudder Repository Added"

  msg_info "Installing Rudder Server"
  apt-get install -y rudder-server-root &>/dev/null
  msg_ok "Rudder Server Installed"

  msg_info "Starting Rudder Service"
  systemctl enable rudder &>/dev/null
  systemctl start rudder &>/dev/null
  msg_ok "Rudder Service Started"
}

start
build_container
description
install_rudder

msg_ok "Completed Successfully!\n"
echo -e "${APP} Server should be reachable by going to the following URL after initial setup completes.
         ${BL}https://${IP}/rudder${CL} \n"
